#!/bin/bash
# just starts the discovery dnsmasq process
set -eux

# TODO(marios): do this with os-svc-install

install-packages dnsmasq dnsmasq-utils
# make sure tftpboot is labelled correctly
mkdir -p /tftpboot
restorecon -R /tftpboot
cat > /lib/systemd/system/discovery-dhcp-dnsmasq.service << eof
[Unit]
Description=Discovery dhcp dnsmasq service
After=openvswitch.service

[Service]
Type=forking
ExecStart=/sbin/dnsmasq --conf-file=/etc/discovery-dhcp/dnsmasq.conf \\

[Install]
WantedBy=multi-user.target
Alias=discovery-dhcp-dnsmasq.service
eof

# Enable the service
os-svc-enable -n discovery-dhcp-dnsmasq
